### ISSUE TITLE
Make all char* parameters const

### ISSUE THREAD

**Issue by ronny332** [jimlawless/map_lib#1]
Hi!

Would it be possible to update the parameter types (char*) to const version (const char*)?
At the source code I can't see any modifications of these parameters, changing them to const shouldn't break anything and suppress a few compiler warnings, which I don't like to cast away or disable.

before:
```
void map_set(struct map_t *m,char *name,char *value);
char *map_get(struct map_t *m,char *name)
```
after:
```
void map_set(struct map_t *m,const char *name,const char *value);
char *map_get(struct map_t *m,const char *name)
```

**Comment by jimlawless** [comment]
Yes.  I'll get to that in the next day or so.

**Comment by ronny332** [comment]
Just as a small update:
Before running `strcasecmp` on an empty value, you should check if it is not falsy. While debugging my own software, I saw a read request at 0x0, caused by `strcasecmp`, which can be avoided by checking for existence.

before:
```
char *map_get(struct map_t *m,const char *name) {
   struct map_t *map;
   for(map=m;map!=NULL;map=map->nxt) {
      if(!strcasecmp(name,map->name)) {
         return map->value;
      }
   }
   return "";
```
after:
```
char *map_get(struct map_t *m,const char *name) {
   struct map_t *map;
   for(map=m;map!=NULL;map=map->nxt) {
      if(!map->name||!strcasecmp(name,map->name)) {
         return map->value;
      }
   }
   return "";
```

Thank you :blush:

**Comment by jimlawless** [comment]
I've updated the library.  Please take a look at the new approach for handling errors that can occur in the functions.
